force-app/main/default/objects/Invitation__c/Invitation__c.object-meta.xml
<CustomObject>
    <description>Use in Invitation App</description>
    <label>Invitation</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invitation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invitations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invitation__c/fields/Event_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Date_and_Time__c</fullName>
    <label>Event Date and Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Event_Map_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_Map_URL__c</fullName>
    <label>Event Map URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Facebook_URL__c.field-meta.xml
<CustomField>
    <fullName>Facebook_URL__c</fullName>
    <label>Facebook URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Respond_By__c.field-meta.xml
<CustomField>
    <fullName>Respond_By__c</fullName>
    <label>Respond By</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/RSVP_Accept_Message__c.field-meta.xml
<CustomField>
    <fullName>RSVP_Accept_Message__c</fullName>
    <label>RSVP Accept Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/RSVP_After_Date_Message__c.field-meta.xml
<CustomField>
    <fullName>RSVP_After_Date_Message__c</fullName>
    <label>RSVP After Date Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/RSVP_Decline_Message__c.field-meta.xml
<CustomField>
    <fullName>RSVP_Decline_Message__c</fullName>
    <label>RSVP Decline Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invitation__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>theme1</fullName>
                <label>Theme 1</label>
            </value>
            <value>
                <fullName>theme2</fullName>
                <label>Theme 2</label>
            </value>
            <value>
                <fullName>theme3</fullName>
                <label>Theme 3</label>
            </value>
            <value>
                <fullName>theme4</fullName>
                <label>Theme 4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invitation_Response__c/fields/Additional_Comments__c.field-meta.xml
<CustomField>
    <fullName>Additional_Comments__c</fullName>
    <label>Additional Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Invitation_Response__c/fields/Number_of_Additional_Guests__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Additional_Guests__c</fullName>
    <label>Number of Additional Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invitation_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joyfully Accept</fullName>
            </value>
            <value>
                <fullName>Regretfully Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Detail__c/Program_Detail__c.object-meta.xml
<CustomObject>
    <label>Program Detail</label>
    <nameField>
        <label>Program Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Detail__c/fields/Invitation__c.field-meta.xml
<CustomField>
    <fullName>Invitation__c</fullName>
    <label>Invitation</label>
    <referenceTo>Invitation__c</referenceTo>
    <relationshipLabel>Program Detail</relationshipLabel>
    <relationshipName>Program_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvitationController.cls
public without sharing class InvitationController {
    
    // Get Invitation details by Id
    @AuraEnabled(cacheable=true)
    public static Invitation__c getInvitationDetailsById(String Id) {
        try {
            return [SELECT Id, Twitter_URL__c, Theme__c, Instagram_URL__c, 
            Greeting_Message__c, Facebook_URL__c, Event_Participants__c,
            Event_Introduction__c, Event_Date_and_Time__c 
            FROM Invitation__c 
            WHERE Id = :Id];
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // Get Invitation details by Id
    @AuraEnabled(cacheable=true)
    public static List<Program_Detail__c> getProgramDetailsByInvitationId(String Id) {
        try {
            return [SELECT Id, Name, Program_Date__c, Program_Start_Time__c, Program_End_Time__c 
            FROM Program_Detail__c 
            WHERE Invitation__c = :Id];
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //Get Invitation address By Id
    @AuraEnabled(cacheable=true)
    public static Invitation__c getInvitationAddress(String Id) {
        try {
            return [SELECT Id, Event_Address__c, Event_Map_URL__c, Contact_Number__c 
            FROM Invitation__c
            WHERE Id= : Id];
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //Get RSVP details By Id
    @AuraEnabled(cacheable=true)
    public static Invitation__c getRSVPDetails(String Id){
        try{
            return [SELECT Id, RSVP_Accept_Message__c, RSVP_After_Date_Message__c, RSVP_Decline_Message__c, Respond_By__c 
            FROM Invitation__c 
            WHERE Id= : Id];
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    //Get Response picklist values
    @AuraEnabled(cacheable=true)
    public static List<String> getResponsePicklistValues(){
        //retrieve the picklist values
       List<String> picklistValues = new List<String>();
       for(Schema.PicklistEntry picklistEntry: Invitation_Response__c.Response__c.getDescribe().getPicklistValues()){
        picklistValues.add(picklistEntry.getValue());
       }
       return picklistValues;
    }

    // Submit Invitation Response
    @AuraEnabled
    public static Boolean submitResponse(Id InvitationId, String Name, String Email, String Phone, String Response, String additionalGuests, String additionalComment){
        try{
            if(InvitationId != null) {
               Invitation_Response__c responseRecord = new Invitation_Response__c(
                    Invitation__c = InvitationId,
                    Name__c = Name,
                    Email__c = Email, 
                    Phone__c = Phone,
                    Response__c = Response,
                    Number_of_Additional_Guests__c = Decimal.valueOf(additionalGuests),
                    Additional_Comments__c = additionalComment
                );
                insert responseRecord;
                return true;
            }
            return false;
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

}